version: '3.8'
services:
  app:
    container_name: Product_Service
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - 5002:5002
    environment:
      - MONGODB_URI=${MONGODB_URI}